import java.io.FileReader;

public class A1 {
    public static void main(String[] args) {
        
        FileReader fr = new FileReader("abc.txt");
        
    }
}

//compilation error because the FileReader(String) constructor of the FileReader class throws the FileNotFoundException, and we also know that FileNotFoundException is a checked exception, 

//FileReader class is a class that extends InputStreamReader and implements Closable, AutoClosable and Readable interfaces
//FileReader class is basically used to read the contents of the file
//it has a constructor FileReader(String) that takes the filepath as argument and creates a FileReader object that is used to read the contents of the file

// FileNotFoundException is a checked exception type class that extends the IOException and implements Serializable interface
// it is generated by the FileReader(String) constructor of the class File Reader when the filename given in the argument is not found

// and it is saying that we can handle the checked exception (so that it will not give compilation error) that is using
// 1. by using try-catch block 
// 2. by representing that method throws exception by writing throws in the method signature

//compilation error as
// A1.java:6: error: unreported exception FileNotFoundException; must be caught or declared to be thrown
//         FileReader fr = new FileReader("abc.txt");
//                         ^
// 1 error
// error: compilation failed